/* Public filters and exact local STL-derived viewer. No external services. */
(()=>{
 const partSearch=document.querySelector('#parts-search');
 if(partSearch)partSearch.addEventListener('input',()=>{let shown=0;document.querySelectorAll('#component-cards .filter-card').forEach(card=>{card.hidden=!card.dataset.filter.includes(partSearch.value.toLocaleLowerCase('ru').trim());if(!card.hidden)shown++});document.querySelector('#parts-empty').hidden=shown>0});
 const cameraSearch=document.querySelector('#camera-search'),group=document.querySelector('#camera-group');
 if(cameraSearch){const filter=()=>{let shown=0;const query=cameraSearch.value.toLocaleLowerCase('ru').trim().replace(/hc-/g,'hc');document.querySelectorAll('#camera-cards .filter-card').forEach(card=>{const scope=group.value==='unknown'?card.dataset.unknown==='true':group.value==='top'?card.dataset.top==='true':!card.dataset.unknown;card.hidden=!scope||!card.dataset.filter.replace(/hc-/g,'hc').includes(query);if(!card.hidden)shown++});document.querySelector('#camera-count').textContent=`Показано: ${shown}`};cameraSearch.addEventListener('input',filter);group.addEventListener('change',filter);filter()}
 const canvas=document.querySelector('#cad-canvas');if(!canvas)return;
 const ctx=canvas.getContext('2d'),status=document.querySelector('#cad-status'),slider=document.querySelector('#cad-explode');
 let mesh=null,yaw=-.5,pitch=.22,drag=null,pending=false;
 const placement={body:[0,0,0],lid:[0,0,70],tray:[0,0,12],camera_baffle:[65,153,53],ir_retainer:[12,37,65],camera_carrier:[35,116,50]};
 const colors={body:[98,111,102],lid:[137,149,138],tray:[87,111,91],camera_baffle:[39,45,39],ir_retainer:[77,87,79],camera_carrier:[82,110,86]};
 function render(){pending=false;if(!mesh)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#e9ede4';ctx.fillRect(0,0,w,h);const scale=Math.min(w/360,h/300),cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),faces=[];
 Object.entries(mesh).forEach(([name,part])=>{const offset=placement[name],explode=Number(slider.value)*(name==='lid'?1:name==='tray'?.4:0);const vertices=part.v.map(v=>{const x=v[0]+offset[0]-65,y=v[1]+offset[1]-95,z=v[2]+offset[2]+explode-37;const a=x*cy+z*sy,b=-x*sy+z*cy;return [a,y*cp-b*sp,y*sp+b*cp]});part.f.forEach(f=>{const a=vertices[f[0]],b=vertices[f[1]],c=vertices[f[2]],nz=(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);if(nz<=.05)return;faces.push({points:[a,b,c],depth:(a[2]+b[2]+c[2])/3,color:colors[name],shade:.93})})});faces.sort((a,b)=>a.depth-b.depth);for(const face of faces){ctx.beginPath();face.points.forEach((p,i)=>{const x=w/2+p[0]*scale,y=h/2-p[1]*scale;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle=`rgb(${face.color.map(c=>Math.round(c*face.shade)).join(',')})`;ctx.fill();ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=.7;ctx.stroke()} }
 function request(){if(!pending){pending=true;requestAnimationFrame(render)}}
 canvas.addEventListener('pointerdown',ev=>{drag=[ev.clientX,ev.clientY];canvas.setPointerCapture(ev.pointerId)});canvas.addEventListener('pointermove',ev=>{if(!drag)return;yaw+=(ev.clientX-drag[0])*.008;pitch=Math.max(-1.3,Math.min(1.3,pitch+(ev.clientY-drag[1])*.008));drag=[ev.clientX,ev.clientY];request()});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);slider.addEventListener('input',request);window.addEventListener('resize',request);
 fetch('assets/case-mesh.json').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(data=>{mesh=data;status.textContent='6 жёстких деталей из CAD. Покупные модули и провода здесь не моделируются.';request()}).catch(()=>{status.textContent='Просмотр недоступен. Выше есть изображения, ниже — STL и STEP для скачивания.'});
})();
